### ISSUE TITLE
Design Doc Review

### ISSUE THREAD

**Issue by bchowdhury00** [hilaryzen/Bagel_Pizza#1]
I really liked how you guys displayed how your data flows between your back and front end, and your component map is very helpful. I was just wondering because you mentioned that someone would be working on database stuff, what are you guys using sqlite3 or mongoDb, and is it going to be a meaningful part of your project? In addition, will you include any conclusions that you've drawn from your visualizations, and will you potentially include that in your end product/presentation?

**Comment by tofr** [comment]
no mongo. Does not play nice with our flask deployments. Please correct me if sqlite3 is not specified/mandated on assignment page...

**Comment by aliceni7** [comment]
> no mongo. Does not play nice with our flask deployments. Please correct me if sqlite3 is not specified/mandated on assignment page...

The assignments page states "You may use CSV/JSON files or an sqlite3 database." so sqlite3 is not mandated.

**Comment by bchowdhury00** [comment]
Ah my mistake
